algoritmo "lista"
// Função :  solicitar lista de compras
// Autor :   caio victor
// Data : 21/10/2020
// Seção de Declarações 
var
listacompras: vetor[1.10] de caractere
cont: inteiro
inicio
//inicio
para cont de 1 ate 10 faca
escreval("Digite o",cont,"o item da lista de compras:")
leia(listacompras[cont])
fimpara

para cont de 1 ate 10 faca
escreval("Lista,item",cont,":",listacompras[cont])
fimpara
fimalgoritmo
